---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: approle
  namespace: default
spec:
  encryptedData:
    foo: AgBYjFcYPlKY5YDMg0TOZSAauTd0jABxhL0LWbL89jL1GTHw0ZOkNs+eIgv3Z7FiXECYOr69HWW1Eukgyfsaz4j73EOaglfJl/lZWRaF35+SDq7sxaRsNuGHM2uXW/L8z7JRwE4gju43FDOv2kH0YP1wXfnQElMmkbPFiWZ3/1EGGGTNdPSGwstSRl4+NsRL0yIFRdtiIUgLUjacVb2lwIxMNl7qOEmJfBQP3cXAMNR20cI13O1lqltE9ha4Lm0ZJ4sPJ89+mVk9wCjDSVA8o9hV5BNAvW7TiREUmJLIog3/FTbhG+Cetbm9r+PYMIawFuBZNRqr/zTgb63t5SsFEPbEBRjsztiBYtaFBZ5nI4/T76GsVjxFu4ArwgHCt/K8UIRNwGzMl9JyqKbZIKb61uRKwHFoZZQ794HHvzL6sDpVSHnslboh7Jjg68V22R++1qp5fg12cP6TF/kwomrt/iRcbLXc2P2vFVwActwyeYCGTeVJRWl4soNjH6f9wg3VT+4wCMR2H8toUNrwi27orHLV2k1ArmHIw2E2Xk9Byl0izD6NOX+X5GA2fDK55xMQegUrrbBX8wwtxz31x6e7Z8pZ7nmfksWVN4QRI1VzPyiC7n8OKAVPtFNKzBGxtB2frLhk32k3hb8c2/JvGkfk0Am3GiFET78W85sLMvw0r4HjiocM8mxL1r3nEeO6AKfrVUYxDp8=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: approle
      namespace: default
