---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: testsecret
  namespace: default
spec:
  encryptedData:
    foo: AgA/Bv6NM/cy6V/3tRSVBMXmv4LjwSWhcpEFLMDBaCJ2LKY1WGDosZ15Nm/bCILF4hRp2Zw25Hef7gH/mOg4jiIP2ak5xnXHaqk+VV1zhnCMPl7D6wVdclBV80sUqABZZea7y9r3j6Oz0qR3KsaQMrk417c/K1C+AM9k7tU/bqv+8xE0ZuUkWPLJcY6tZQhH/k1m+aplmxN3UEgpFZ0hXLuQtB0t2laBR5u83PLge0QkVyRiIafxml9oP7FZtaafITtD51Kg1mydG6jgGeMXR144sZzWS1xDrzJGT1ZCQHVx6qWhwiJps5JwQyrpg6A/9wTkkyD4+mu1/MKLRHF9BCHCorsulDkiQr5rtZ68/1oKvTYWgrthb42UzJRL40YGaEMAFLXHgNfg5w98fyHPRnWO/mMIfsE7wp02SkY8ouTnYA6LS+wUXUMa//Juu2EH6RmVgMUbjAH6NfJYrJPhM87ZDg5DeQP6LTMzeMZFvqLkG9utKdI6n2S8BO+A/WzHErCTnAxth0yc2sPoZmbu7WRBbq3saaT2Dj3RJuDgBTcjmDYVDdJCwhRmPipqoiTzMhr0mTTPI4J6YIMKfoG6EwoBoYAFAfsOobzqcc0MzmMJu5dS7sVvIyFZ8XJ6/AdGgZZkxzyEXjJwEECyB08RNfMXSta31/T2rXtH4xc0I9FZ5bhA4zePY80DIPA0WVS3/NlJR54=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: testsecret
      namespace: default
