---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: approle
spec:
  encryptedData:
    foo: AgCVcUz9H7DcsgwDpLaAlDcXQ4KOMqLA7XYVVJgYEfixl1pMiwjZ6bwUHRZpLsA87rrM/uxsRuVReRUKq/e4bUz7KG7foCKYXuc8UP6LJ7dYTIZGjoPJeWPulo0HjG4kYpOvHg5/Zl533IZJsaNXCJA1lko6tf3HawcEhrDiDVDumE9yuIMeQPFKSSy7dHRSVXgmrdvEmL8f0PzWX2lM4wrMXbdg/G8PSrJMCMt/PY598u+IgMHh0e/VYVCFIW5WrrlENwe9IDhXQcHoqMv3WqBDXOnCVJsrSEVbb1BFr1byF2TfgkIE23tHwysO02/tSHurWiGgaUurvBV7cNnYo8i1pcmzdSjfc8WJOzK+E3kzmIoz9oEJbMB8bx8hv+JnouL2drZQB0NzvOlcM9JVAyiSEOODM9Se6fE1yBMkrPxer9o5ckwtecz3ws4qK1hyZoxOtzjHnhsOXBDrOn5/nXiJzcdL72lqRQV5hnnpbtNpj4aWVp1QT8F+ETfaJjHYl+Rsxp8k+pJgaYtmSvYORECPgEV7qT6ReWDfTnOdQ1+R+H/cu7TpwKTHY9dXoenb/U6a5MpAzwqFgSPTQt9IPu137iKnweVVGWIXbxH2SHBvCUJGPnvGvYZSS4e1N6pf/0+VkMd+kZnn55DNFnRAMauH+MO6/iKHOHr4EgKWsk3gChEAmFo7KP+M++1Krj8MR1FWSqg=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: approle
