---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: registry-creds
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgA0zZjYEmsY9Yx6uB7JKbEF6RzsQlLwKs4Zm3bnZauLZkIKftWi7xd4qTc5YzGGbCLXq0HqtxnbVAESlRZlDIRFfbDX4rbQ9FH4xOS29eLY5W/lWpVzwcfXDeT2BvXw+LDyQeQ5yXa3XYwccNjg4XBrHxLU8tuCIJ981W5MuW/DTMVt7vZ12pvZrkXpKDOgNZtyPBnxQscEkfuG2rnXug2qkCa+lkpGqsSFqMz8zff5Yuq48/fyYLkSQsRkmzwY3q++Pd3xM467henMM4ZYOYU/hYrIT1ZUOPGqd82V+SPW6JBSEc7ORmDn/sD2Y/yuBFmUEf/xYtX4JsCePr21s4x+bjJuzyPFaJLdcYnWWlj7o6xRMAL3JE6FnGTEt3I4TfsLRu4x0idL8+m6uR+LujR1VwxI1BcIy8+vi/8p44SlEzsK/wXiOR5+vlv/0CeR2Zav1OKJBcFapVFY/DzMWlsAU3z/t5RPG3T+dGQ3Pv3K1XPO+/CRvuFaFAEjalGK70zmZm++q+Bb/7xUAaaxe+2dNkiAl6oCXPMCzRh6r73RUec4Q7aSg4s+l4HMXmvFEYOUekEQPkVWYuMeV9l4tcVDiJkxJ+KSlnp+tjAaS+cK3Ef6nJafZH+kEQPyjCY+BPyDAldr3iPtJu2u+QWK4WrquAm4swf2hM40QAZy5vIoeDSp/FMhg0QIw/LAehsMRl65o7+8x8W/tzuQtsRb5aRf3SsIyJBIXs19SebjzJ2naWoYvhFGv/NbwQRo28NNvicy1dTeMAIlZf8QTGSyDTEy553zCx5+RL3NBlyYM+sRc2D4S1LoFy1VcGql4qZT
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: registry-creds
      namespace: default
    type: kubernetes.io/dockerconfigjson
