---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: registry-creds
  namespace: kube-system
spec:
  encryptedData:
    .dockerconfigjson: AgB2w/a5Y+IoyGazwjXJEbfEKlRzNdfBVWz/WFAQBRVL/G7ZcUYvTS+iQGgcbdiD6ApE/wDqtMO8D/YhRayXh5qW+qb/ZNOePbzz1NSoXoc0LxLV2G4lcBNhWhL8dOL5XGRPmfKQRjVwBY5P44REZtUtf0jaLd7zphgPySi52FGUABFXIRnRJHdLo5V1ZXKl6ENsR3tctsaBvFrvhSF7DHyJgYIBY4Rb8X6C3XCeTvqDo9+RMeXYkhEorN7lEfuyMBp59WUu1bpRhMnSl+vyLe3FfyUwMuxdutyejRVByqy2msLZvDgl4LJsAH6OSadygUyOZ01MFHGJH59eLUuwIrSb97ZuQ73H6fNzW0bJvEbGxl0DFACZ7nWR11FlK6vODdRpCI+kXtcChzEENrxLMirnD7xXBptduFgbq9JheC6YOUc6l7VGg8BE6MoOKO3FlqSIMsiJcYDf+8mb5GtrSDJ8G3igdIbpUmy8+r8sQZruErwjNOeUqkXtInHR8VeAK1ZuX265cRIb5BdlcytAEZ/BNtAyiAm76bJeqqNQ2Y0SCrhb8ciK3numC8NuewKQoeJ9U+hZtv0hTPi35UsduKSn/4zVf1vWysa3JXft+DTpvGRHHj8+seIEscEFknorqZQt01QP2dDdSioMU4UfRK2j8Rh9KbsNLV3X7I8J51VnS/bS08Snp1GPB3T8o+0nOo7nZ0Chh855cOKRgNZeXU65TwXTXWgTykV+tuAA1Wr2pxVZfuIPdQOYH+juQebx1M16pJ0V3kFBwVbmzpyoN5Pc+YQ/YPIDQoM/ApOFpY1WKP+DVrVoGtFlJTVKiqNy
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: registry-creds
      namespace: kube-system
    type: kubernetes.io/dockerconfigjson
