apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-config
  namespace: ns1
spec:
  destination:
    name: supervisor
  project: default
  source:
    path: argo
    repoURL: https://github.com/dstoffel/testvks.git
    targetRevision: HEAD
